name: SWE Agent Auto Issue Detection and Fix

on:
  schedule:
    # Run every day at 8 AM UTC
    - cron: '0 8 * * *'
  workflow_dispatch: # Allow manual trigger
  push:
    branches: [ main ]
    paths:
      - '**/*.py'
      - 'requirements.txt'

jobs:
  swe-agent-auto-fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Setup SWE Agent
      run: |
        # Clone and install SWE Agent
        git clone https://github.com/princeton-nlp/SWE-agent.git swe-agent
        cd swe-agent
        pip install -e .

    - name: Run SWE Agent with Free Hugging Face Model
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        cd swe-agent
        
        # Use free Hugging Face model instead of paid OpenAI
        # DeepSeek-Coder is a powerful free model good for code tasks
        python -m sweagent.agent.run \
          --model_name "deepseek-ai/deepseek-coder-6.7b-instruct" \
          --data_path "Scan this repository for any bugs, issues, or problems. If you find any issues, create a detailed GitHub issue describing the problem, then create a pull request with a fix. Focus on: 1) Test failures, 2) Code that could crash or cause errors, 3) Security vulnerabilities, 4) Code quality issues." \
          --repo_path "../" \
          --config_file "config/default_from_url.yaml" \
          --apply_patch_locally \
          --github_token "$GITHUB_TOKEN" \
        || echo "SWE Agent completed its analysis and fixes using free Hugging Face model"

    - name: Summary
      run: |
        echo "🤖 SWE Agent has completed its autonomous analysis using FREE DeepSeek-Coder model"
        echo "✅ Scanned repository for issues"
        echo "📝 Created GitHub issues for any problems found"
        echo "🔧 Applied fixes and created pull requests"
        echo "💰 No API costs - completely free with Hugging Face!"
        echo "👀 Check the Issues and Pull Requests tabs for SWE Agent's work"