name: SWE Agent Autonomous Bug Detection and Fix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 9 * * 1'  # Weekly on Mondays at 9 AM UTC

jobs:
  swe-agent-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install SWE Agent
      run: |
        git clone https://github.com/princeton-nlp/SWE-agent.git
        cd SWE-agent
        pip install -e .
        
    - name: Run SWE Agent with Claude Sonnet 4
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd SWE-agent
        sweagent run \
          --agent.model.name=claude-sonnet-4-20250514 \
          --agent.model.per_instance_cost_limit=2.00 \
          --env.repo.github_url=https://github.com/${{ github.repository }} \
          --problem_statement.text="Please scan this repository for bugs, create GitHub issues for any problems found, and create pull requests with fixes. Focus on potential runtime errors, logic bugs, and code quality issues." \
          --actions.open_pr
          
    - name: Summary
      if: always()
      run: echo "SWE Agent has completed its autonomous analysis and bug fixing process"